server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:default_2131secret}
  lifetime: ${JWT_LIFETIME:3600000}
  issuer: ${JWT_ISSUER:user_service}

## DB config
spring:
  application:
    name: user_service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ca-user?currentSchema=ca-user
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1085}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true



## OpenApi config
springdoc:
  packagesToScan: org.brain.user_service.controller
  pathsToMatch:
    - /api/v1/auth/**
    - /api/v1/validation/**




